# Generated by Django 5.0.6 on 2024-05-10 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 8, 4, 29, 847534, tzinfo=datetime.timezone.utc)),
        ),
    ]
